name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  backend:
    runs-on: ubuntu-18.04

    strategy:
      fail-fast: true
      matrix:
        php-versions: ['7.4']

    steps:
      - name: Setup PHP, extensions and composer with shivammathur/setup-php
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
        env:
          update: true

      - uses: actions/checkout@v2

      - name: Composer install
        run: composer install --prefer-dist --no-progress --no-plugins --no-scripts

      - name: Run unit tests
        run: vendor/bin/phpunit --testdox

